# a minimal test environment for janki
# Copyright (c) 2021 University System of Georgia and janki contributors
# Distributed under the terms of the BSD-3-Clause License.
name: janki-test

channels:
  - https://conda.anaconda.org/conda-forge

dependencies:
  ### janki-test
  # build
  - doit
  - pip
  - python >=3.7
  # run
  - jupyterlab >=3.0.14
  - genanki
  - zipp
  # - ankipandas  # TODO replace once available
  - randomfiletree
  - pip:
      - ankipandas
  # unit test
  - coverage
  - hypothesis-jsonschema
  - pytest-html
  - pytest-tornasync
  ### janki-test
