# a full development, test, and documentation environment for janki
# Copyright (c) 2021 University System of Georgia and janki contributors
# Distributed under the terms of the BSD-3-Clause License.
name: janki-dev

channels:
  - https://conda.anaconda.org/conda-forge

dependencies:
  # branding
  - jupyterlab-gt-coar-theme
  # extras
  - ipydrawio-export
  - jupyterlab-markup
  - jupyterlab-tour
  - genson
  # lint
  - isort
  - black
  - pyflakes
  # extra dev
  - nodejs >=14,<15
  - twine
  ### janki-test
  # build
  - doit
  - pip
  - python >=3.7
  # run
  - jupyterlab >=3.0.14
  - genanki
  - zipp
  # - ankipandas  # TODO replace once available
  - randomfiletree
  - pip:
      - ankipandas
  # unit test
  - coverage
  - hypothesis-jsonschema
  - pytest-html
  - pytest-tornasync
  ### janki-test
  ### janki-docs
  - pydata-sphinx-theme >=0.6.2
  - myst-nb
  - sphinx-jsonschema
  - pytest-check-links
  - sqlalchemy <1.4
  ### janki-docs
