# a full development, test, and documentation environment for janki
# Copyright (c) 2021 University System of Georgia and janki contributors
# Distributed under the terms of the BSD-3-Clause License.
name: janki-dev

channels:
  - https://conda.anaconda.org/conda-forge

dependencies:
  # build
  - doit
  - nodejs >=14,<15
  - pip
  - python >=3.7
  - twine
  # run
  - jupyterlab >=3.0.14
  - randomfiletree
  # - ankipandas  # TODO replace once available
  - pip:
      - ankipandas
  # extras
  - ipydrawio-export
  - jupyterlab-markup
  - jupyterlab-tour
  # demo
  - jupyterlab-gt-coar-theme
  # lint
  - isort
  - black
  - pyflakes
  # unit test
  - pytest-cov
  - pytest-html
  - pytest-tornasync
  - hypothesis-jsonschema
  # acceptance test
  - firefox =78
  - geckodriver
  - robotframework-jupyterlibrary
  # docs
  - pydata-sphinx-theme >=0.6.2
  - myst-nb
  - sphinx-jsonschema
  - pytest-check-links
  - sqlalchemy <1.4
