#!/usr/bin/env bash

set -eux

# do a proper activation
source activate "${NB_PYTHON_PREFIX}"

# some things we just don't need to do on binder
export IN_BINDER=1

jlpm cache clean

doit -n8 binder || doit binder
