#!/usr/bin/env bash
# Copyright (c) 2021 University System of Georgia and janki contributors
# Distributed under the terms of the BSD-3-Clause License.
set -eux

# do a proper activation
source activate "${NB_PYTHON_PREFIX}"

# some things we just don't need to do on binder
export IN_BINDER=1

jlpm cache clean

doit -n8 binder || doit binder
