# a docs environment for janki

# Copyright (c) 2021 University System of Georgia and janki contributors
# Distributed under the terms of the BSD-3-Clause License.
name: janki-docs

channels:
  - https://conda.anaconda.org/conda-forge

dependencies:
  ### janki-docs
  - pydata-sphinx-theme >=0.6.2
  - myst-nb
  - sphinx-jsonschema
  - pytest-check-links
  - sqlalchemy <1.4
  ### janki-docs
  ### janki-test
  # build
  - doit
  - pip
  - python >=3.7
  # run
  - jupyterlab >=3.0.14
  - randomfiletree
  # - ankipandas  # TODO replace once available
  - pip:
      - ankipandas
  # unit test
  - hypothesis-jsonschema
  - pytest-cov
  - pytest-html
  - pytest-tornasync
  ### janki-test
